AWSTemplateFormatVersion: 2010-09-09
Description: Application Example

Parameters:

  AllowedIPs:
    Description: IP addresses allowed to access the web server on th example instance
    Type: String
    Default: ''

  AvailabilityZones:
    Description: >-
      List of Availability Zones to use for the subnets in the VPC
    Type: String

  VPCCIDR:
    AllowedPattern: >-
      ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.0.0/16
    Description: CIDR block for the VPC
    Type: String

  PublicSubnet1CIDR:
    AllowedPattern: >-
      ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.128.0/20
    Description: CIDR block for the public DMZ subnet 1 located in Availability Zone 1
    Type: String

  PublicSubnet2CIDR:
    AllowedPattern: >-
      ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.144.0/20
    Description: CIDR block for the public DMZ subnet 2 located in Availability Zone 2
    Type: String

  CfnStacksTemplates:
    Description: Template service base URL
    Type: String
    Default: 'https://s3.us-east-2.amazonaws.com/cfn-stacks.com/templates'

  CreateInstance:
    Description: Should an EC2 instance be created within the VPC?
    Type: String
    Default: false
    AllowedValues:
      - true
      - false

Conditions:

  CreateInstance: !Equals [ 'true', !Ref CreateInstance ]

Mappings:
  Constants:
    ValueOf:
      VpcTemplateVersion: 'release/com/cfnstacks/cfn-public-only-vpc/0.0.11'
      AppTemplateVersion: 'release/com/cfnstacks/cfn-app-example/0.0.1'
      TemplateTimeout: 15

Resources:

  VPC:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: !Sub
        - '${CfnStacksTemplates}/${TemplateVersion}/public-only-vpc.yaml'
        - TemplateVersion: !FindInMap [ Constants, ValueOf, VpcTemplateVersion ]
      TimeoutInMinutes: !FindInMap [ Constants, ValueOf, TemplateTimeout ]
      Parameters:
        AvailabilityZones: !Ref AvailabilityZones
        VPCCIDR: !Ref VPCCIDR
        PublicSubnet1CIDR: !Ref PublicSubnet1CIDR
        PublicSubnet2CIDR: !Ref PublicSubnet2CIDR

  App:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      # @templatePath@ - Is a token that gets replaced by the plugin with the namespace and version of this project
      # You'll need to run the publish task to see changes but you won't have to update the version string
      # https://cfn-stacks.com/docs/artifacts3-plugin/latest/index.html#build
      #TemplateURL: !Sub '${CfnStacksTemplates}/@templatePath@/app.yaml'

      # For this example we're using a release version as snapshots are deleted in the public repo after 30 days
      # but the example above would be more common in practice
      TemplateURL: !Sub
        - '${CfnStacksTemplates}/${TemplateVersion}/app.yaml'
        - TemplateVersion: !FindInMap [ Constants, ValueOf, AppTemplateVersion ]
      TimeoutInMinutes: !FindInMap [ Constants, ValueOf, TemplateTimeout ]
      Parameters:
        AllowedIPs: !Ref AllowedIPs
        InstanceSubnetId: !If [ CreateInstance, !GetAtt VPC.Outputs.PublicSubnet1ID , !Ref 'AWS::NoValue' ]
        VpcId: !GetAtt VPC.Outputs.VPCID

Outputs:
  CfnStacksId:
    Description: cfn-stacks.com artifact id
    Value: @artifactId@
  CfnStacksVersion:
    Description: cfn-stacks.com artifact version
    Value: v@version@
  VpcId:
    Description: VPC ID
    Value: !Ref VPC
  WebServerDnsName:
    Condition: CreateInstance
    Description: WebServer Link
    Value: !GetAtt App.Outputs.WebServerDnsName